# Generated by Django 4.2.27 on 2026-01-21 23:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Unnamed Session", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("messages", models.JSONField(default=list)),
                (
                    "model_name",
                    models.CharField(default="gemini-2.5-flash", max_length=100),
                ),
                ("selected_tools", models.JSONField(default=list)),
                ("selected_mcp_servers", models.JSONField(default=list)),
            ],
        ),
    ]
