# Generated by Django 4.2.30 on 2026-09-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_db_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='model_name',
            field=models.CharField(default='gemini-3.8-flash', max_length=100),
        ),
    ]
