"""
Django settings for gnnpcsaftchat project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("GNNPCSAFTCHAT_SECRET_KEY", default="ABCDEFG")

PLATFORM = config("GNNPCSAFTCHAT_PLATFORM", default="desktop")

MCP_SERVER_CONFIG = config(
    "GNNPCSAFTCHAT_MCP_SERVER_CONFIG", default=BASE_DIR / "mcp_server.json", cast=Path
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("GNNPCSAFTCHAT_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "GNNPCSAFTCHAT_ALLOWED_HOSTS",
    default="*,*",
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sessions",
    "chat",
    "debug_toolbar",
    "bootstrap5",
    "fontawesomefree",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

# Django Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION = "app.wsgi.application"


ASGI_APPLICATION = "app.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_PATH = config("GNNPCSAFTCHAT_DB_PATH", default=BASE_DIR / "gnnpcsaft.db")

DB_CHAT_PATH = config(
    "GNNPCSAFTCHAT_DB_CHAT_PATH", default=BASE_DIR / "gnnpcsaft.chat.db"
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "productionfiles"

STATICFILES_DIRS = []


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SECURE_SSL_REDIRECT = False

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = config(
    "GNNPCSAFTCHAT_DOMAIN_NAME",
    default="https://*, http://*",
    cast=Csv(),
)

# Logging
# https://docs.djangoproject.com/en/4.2/topics/logging/

LOG_PATH = config("GNNPCSAFTCHAT_LOG_PATH", default=BASE_DIR, cast=Path)
LOG_LEVEL = config("GNNPCSAFTCHAT_LOG_LEVEL", default="WARNING")

assert isinstance(LOG_PATH, Path), "LOG_PATH must be a Path object"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{name} {levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": LOG_PATH / "gnnpcsaftchat.log",
            "level": LOG_LEVEL,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": LOG_LEVEL,
        },
    },
    "loggers": {
        # Root logger - currently logs only to file
        "": {
            "level": LOG_LEVEL,
            # You could add 'console' here if you want logs in both places:
            # "handlers": ["file", "console"],
            "handlers": ["file"],
        },
    },
}

# ollama config

os.environ["OLLAMA_API_BASE"] = str(
    config("GNNPCSAFTCHAT_OLLAMA_API_BASE", default="http://localhost:11434")
)
