name: Release Ubuntu DEB

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      KIVY_NO_ARGS: "1"
      KIVY_NO_CONSOLELOG: "1"
      KIVY_AUDIO: "dummy"
      SDL_VIDEODRIVER: "x11"

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0 libsm6 libxrender1 libxext6 libegl1 libmtdev1 xvfb libnss3

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          activate-environment: true

      - name: Build DEB
        run: |
          xvfb-run -a bash ./release-workflow.sh --skip-upload

      - name: Publish release asset
        uses: softprops/action-gh-release@v3
        with:
          files: app_pkg/dist/*.deb
          fail_on_unmatched_files: true
          generate_release_notes: false
          draft: true
